# Generated by Django 3.0.8 on 2020-12-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0003_auto_20201221_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
