# Generated by Django 3.0.8 on 2020-12-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0005_post_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
